src/Entity/AdminLogin.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
//use Captcha\Bundle\CaptchaBundle\Validator\Constraints as CaptchaAssert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminLoginRepository")
 * @UniqueEntity("email", message = "Un compte a déjà été enregistré avec cette adresse email.")
 */
class AdminLogin implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 6,
     *      max = 100,
     *      minMessage = "Votre nom d'utilisateur doit comporter au moins 6 caractères. {{ limit }}",
     *      maxMessage = "Votre nom d'utilisateur ne peut comporter plus de 100 caractères. {{ limit }}"
     * )
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 8,
     *      max = 100,
     *      minMessage = "Votre mot de passe doit comporter au moins 8 caractères.",
     *      maxMessage = "Votre mot de passe ne peut comporter plus de 100 caractères."
     * )
     */
    private $password;

    /**
     * @ORM\Column(type="integer")
     */
    private $level;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $profil;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cle_activation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_limite_activation;

    // /**
    //  * @CaptchaAssert\ValidSimpleCaptcha(
    //  *      message = "CAPTCHA validation failed, try again."
    //  * )
    //  */
    // protected $captchaCode;

    // /**
    //  * @ORM\Column(type="string", length=255, nullable=true)
    //  */
    // private $cle_recup_mdp;

    // public function getCaptchaCode()
    // {
    //     return $this->captchaCode;
    // }

    // public function setCaptchaCode($captchaCode)
    // {
    //     $this->captchaCode = $captchaCode;
    // }

    public function getId() : ? int
    {
        return $this->id;
    }

    public function getUsername() : ? string
    {
        return $this->username;
    }

    public function setUsername(string $username) : self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword() : ? string
    {
        return $this->password;
    }

    public function setPassword(string $password) : self
    {
        $this->password = $password;

        return $this;
    }

    public function getLevel() : ? int
    {
        return $this->level;
    }

    public function setLevel(int $level) : self
    {
        $this->level = $level;

        return $this;
    }

    public function getCreationDate() : ? \DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date) : self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    // IMPLEMENTER LES INTERFACES 

    public function getRoles()
    {
        if ($this->level >= 2)
            return ['ROLE_ADMIN', 'ROLE_MEMBRE'];
        elseif ($this->level = 1)
            return ['ROLE_MEMBRE'];
        else
            return [];
    }

    public function eraseCredentials()
    {
    }

    public function getSalt()
    {
            // The bcrypt and argon2i algorithms don't require a separate salt.
            // You *may* need a real salt if you choose a different encoder.
        return null;
    }
    /** @see Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
                // see section on salt below
                // $this->salt,
        ));
    }

    /** @see Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->username,
            $this->password,
                // see section on salt below
                // $this->salt
        ) = unserialize($serialized);
    }

    public function getPrenom() : ? string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom) : self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom() : ? string
    {
        return $this->nom;
    }

    public function setNom(string $nom) : self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail() : ? string
    {
        return $this->email;
    }

    public function setEmail(string $email) : self
    {
        $this->email = $email;

        return $this;
    }

    public function getProfil() : ? string
    {
        return $this->profil;
    }

    public function setProfil(string $profil) : self
    {
        $this->profil = $profil;

        return $this;
    }

    public function getCleActivation() : ? string
    {
        return $this->cle_activation;
    }

    public function setCleActivation(string $cle_activation) : self
    {
        $this->cle_activation = $cle_activation;

        return $this;
    }

    public function getDateLimiteActivation() : ? \DateTimeInterface
    {
        return $this->date_limite_activation;
    }

    public function setDateLimiteActivation(\DateTimeInterface $date_limite_activation) : self
    {
        $this->date_limite_activation = $date_limite_activation;

        return $this;
    }

    public function getCleRecupMdp() : ? string
    {
        return $this->cle_recup_mdp;
    }

    public function setCleRecupMdp(? string $cle_recup_mdp) : self
    {
        $this->cle_recup_mdp = $cle_recup_mdp;

        return $this;
    }
}

src/Controller/AdminLoginController.php
<?php

namespace App\Controller;

use App\Entity\AdminLogin;
use App\Form\AdminLoginType;
use App\Repository\AdminLoginRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Doctrine\Common\Persistence\ObjectManager;


/**
 * @Route("/signup")
 */
class AdminLoginController extends AbstractController
{
    /**
     * @Route("/index", name="admin_login_index", methods={"GET"})
     */
    public function index(AdminLoginRepository $adminLoginRepository) : Response
    {
        return $this->render('admin_login/index.html.twig', [
            'admin_logins' => $adminLoginRepository->findAll(),
        ]);
    }

    /**
     * @Route("/", name="admin_login_new", methods={"GET","POST"})
     */
    public function new(Request $request, \Swift_Mailer $mailer) : Response
    {
        $adminLogin = new AdminLogin();
        $form = $this->createForm(AdminLoginType::class, $adminLogin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $adminLogin->setCreationDate(new \DateTime);
            $adminLogin->setLevel(0);

            $passwordNonHashe = $adminLogin->getPassword();
            $passwordHashe = password_hash($passwordNonHashe, PASSWORD_BCRYPT);
            $adminLogin->setPassword($passwordHashe);

            $cleActivation = md5(uniqid());
            $adminLogin->setCleActivation($cleActivation);
            $adminLogin->setDateLimiteActivation(new \DateTime("+1 day"));

            $email = $adminLogin->getEmail();
            $urlActivation = $this->generateUrl("activation", [], UrlGeneratorInterface::ABSOLUTE_URL);

            $prenom = $adminLogin->getPrenom();
            $nom = $adminLogin->getNom();
            $body = "<body style='text-align:center'><h3 style='color:red'>Bonjour, $prenom ! Votre demande d'inscription a bien été enregistrée.</h3>
            <p>Veuillez la confirmer en cliquant sur ce lien</p>
            <p><a href='$urlActivation?email=$email&cleActivation=$cleActivation'>ACTIVER MON COMPTE</a></p>
            <p>Merci et à bientôt !</p>
            <p style='font-weight:bold'>Swann</p>
            </body>";

            $message = (new \Swift_Message("Votre adhésion au site de Swann Xerri"))
                ->setFrom("contact@swannxerri.com")
                ->setTo($adminLogin->getEmail())
                ->setBody($body, "text/html");

            $mailer->send($message);

            $adminBody = "<body style='text-align:center'><h3>Bonjour, Swann ! $prenom $nom a acheté votre formation.</h3>
            <p>Veuillez vérifier la bonne exécution de la transaction dans votre compte PayPal, ainsi que la présence de ce nouveau membre dans votre interface administrateur.</p>
            </body>";

            $adminMessage = (new \Swift_Message("Vous avez un nouveau membre"))
                ->setFrom($adminLogin->getEmail())
                ->setTo("shinkansen13@gmail.com")
                ->setBody($adminBody, "text/html");

            $mailer->send($adminMessage);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($adminLogin);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('admin_login/new.html.twig', [
            'admin_login' => $adminLogin,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/activation", name="activation", methods={"GET","POST"})
     */
    public function activation(AdminLoginRepository $adminLoginRepository, Request $request, \Swift_Mailer $mailer) : Response
    {

        $email = $request->get("email");
        $cleActivation = $request->get("cleActivation");

        if (($email != "") && ($cleActivation != "")) {
            $userCherche = $adminLoginRepository->findOneBy(["email" => $email]);
            if ($userCherche) {

                if ($cleActivation == $userCherche->getCleActivation()) {
                    $dateFin = $userCherche->getDateLimiteActivation();
                    $timestampFin = $dateFin->getTimeStamp();
                    $timestampActuel = time();
                    if ($timestampFin > $timestampActuel) {

                        $userCherche->setLevel(1);
                        $userCherche->setCleActivation(md5(uniqid()));
                        $userCherche->setDateLimiteActivation(new \DateTime("+ 1 day"));

                        $entityManager = $this->getDoctrine()->getManager();
                        $entityManager->flush();

                        $messageConfirmation = "Merci, votre compte est désormais actif.";
                        return $this->redirectToRoute('membre');
                    } else {
                        $messageConfirmation = "La date de validité de la clé d'activation a expiré. Veuillez recommencer votre inscription.";
                    }
                }
            } else {
                $messageConfirmation = "Désolé, Vous n'êtes pas dans notre base de données.";
            }
        }

        dump($_REQUEST);
        dump(" $email, $cleActivation ");

        return $this->render('admin_login/activation.html.twig', [
           // 'articleFooter' => $articleFooter,
            'email' => $email,
            'cleActivation' => $cleActivation,
            'messageConfirmation' => $messageConfirmation ?? "",
        ]);
    }

    /**
     * @Route("/lostpw", name="lostpw", methods={"GET","POST"})
     */
    public function lostpw(Request $request, AdminLoginRepository $adminLoginRepository, ObjectManager $manager, \Swift_Mailer $mailer) : Response
    {
        $email = $request->get("email");
        $adminLogin = null;
        if ($email != "") {
            $adminLogin = $adminLoginRepository->findOneBy(["email" => $email]);
        }
        if ($adminLogin != null) {

            $cleActivation = md5(uniqid());
            $adminLogin->setCleActivation($cleActivation);
            $adminLogin->setDateLimiteActivation(new \DateTime("+1 day"));

            $email = $adminLogin->getEmail();
            $urlActivation = $this->generateUrl("resetpw", [], UrlGeneratorInterface::ABSOLUTE_URL);

            $prenom = $adminLogin->getUsername();
            $body = "<body style='text-align:center'><h3>Bonjour, $prenom ! Votre demande de réinitialisation du mot de passe a été prise en compte.</h3>
            <p>Cliquez sur le lien ci-dessous pour accéder au formulaire.</p>
            <p><a href='$urlActivation?email=$email&cleActivation=$cleActivation'>RÉINITIALISER MON MOT DE PASSE</a></p>
            <p>Si vous n'avez pas demandé une réinitialisation du mot de passe, contactez l'administrateur du site.</p>
            <p>Contact : <a href='shinkansen13@gmail.com'>shinkansen13@gmail.com</a></p>
            </body>";

            $adminMessage = (new \Swift_Message("Swann Xerri - Réinitialisation de votre mot de passe"))
                ->setFrom("shinkansen13@gmail.com")
                ->setTo($adminLogin->getEmail())
                ->setBody($body, "text/html");

            $mailer->send($adminMessage);

            $manager->persist($adminLogin);
            $manager->flush();

            $messageConfirmation = "Veuillez vérifier votre boîte mail.";
        }

        return $this->render('admin_login/lostpw.html.twig', [
            'messageConfirmation' => $messageConfirmation ?? "",
        ]);
    }

    /**
     * @Route("/resetpw", name="resetpw", methods={"GET","POST"})
     */
    public function resetpw(Request $request, AdminLoginRepository $adminLoginRepository, ObjectManager $manager, \Swift_Mailer $mailer) : Response
    {
        $email = $request->get("email");
        $cleActivation = $request->get("cleActivation");
        $password = $request->get("password");
        $passwordConfirm = $request->get("password-confirm");

        $adminLogin = null;

        if ($email != "") {
            $adminLogin = $adminLoginRepository->findOneBy(["email" => $email]);
        }

        if ($adminLogin != null) {
            if ($email == $adminLogin->getEmail()) {
                if ($cleActivation == $adminLogin->getCleActivation()) {
                    if ($password != "" && $passwordConfirm != "") {
                        if ($password == $passwordConfirm) {

                            $passwordHashe = password_hash($password, PASSWORD_BCRYPT);
                            $adminLogin->setPassword($passwordHashe);

                            $prenom = $adminLogin->getUsername();
                            $body = "<body style='text-align:center'><h3>Bonjour, $prenom ! Votre mot de passe a été réinitialisé avec succès.</h3>
            <p>Si vous n'êtes pas à l'origine de cette demande, contactez l'administrateur du site.</p>
            <p>Contact : <a href='shinkansen13@gmail.com'>shinkansen13@gmail.com</a></p>
            </body>";

                            $adminMessage = (new \Swift_Message("Swann Xerri - Votre mot de passe a été réinitialisé"))
                                ->setFrom("shinkansen13@gmail.com")
                                ->setTo($adminLogin->getEmail())
                                ->setBody($body, "text/html");

                            $mailer->send($adminMessage);

                            $adminLogin->setPassword($passwordHashe);
                            $manager->persist($adminLogin);
                            $manager->flush();

                            $messageConfirmation = "Votre mot de passe a été réinitialisé avec succès.";
                        }
                    }
                }
            }
        }

        return $this->render('admin_login/resetpw.html.twig', [
            'email' => $email,

templates/admin_login/_delete_form.html.twig
<form method="post" action="{{ path('admin_login_delete', {'id': admin_login.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette entrée ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin_login.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/admin_login/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn button">{{ button_label|default("Je m'inscris") }}</button>
{{ form_end(form) }}

templates/admin_login/activation.html.twig
{% extends 'base.html.twig' %}

{% block title %}ACTIVATION{% endblock %}

{% block body %}
{% block header %}{% endblock header %}
{% block dashboard %}{% endblock dashboard %}
<div class="container">
    <main role="main" class="col">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2 h2-swann">Formulaire d'activation de compte</h1>
        </div>

        <form method="POST">
            <label for="email">Votre email</label>
            <input class="form-control mb-2" type="email" name="email" value="{{ email }}">
            <label for="cleActivation">Votre clé d'activation</label>
            <input class="form-control mb-2" type="text" name="cleActivation" value="{{ cleActivation }}">
            <button class="btn btn-primary" type="submit">Activer mon compte</button>
            
            <!-- JE DEMANDE UN TOKEN DE SECURITY CONTRE CSRF -->
            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
            <div>
                {{ messageConfirmation ?? "" }}
            </div>
        </form>

        </main>
</div> {# end container-fluid #}

    <script>window.setTimeout(function(){
        window.location.href = "http://127.0.0.1:8000/membres/";
    }, 1000);</script>
{% endblock %}

templates/admin_login/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Édition des utilisateurs{% endblock %}

{% block body %}
    <h1>Édition d'un utilisateur</h1>

    {{ include('admin_login/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('admin_login_index') }}">Retour à la liste</a>

    {{ include('admin_login/_delete_form.html.twig') }}
{% endblock %}

templates/admin_login/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des utilisateurs{% endblock %}

{% block body %}
<div class="container-fluid">
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">Liste des utilisateurs</h1>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
                <th>Id</th>
                <th>Utilisateur</th>
                <th>Niveau</th>
                <th>Date de création</th>
                <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          {% for admin_login in admin_logins %}
            <tr>
                <td>{{ admin_login.id }}</td>
                <td>{{ admin_login.username }}</td>
                <td>{{ admin_login.level }}</td>
                <td>{{ admin_login.creationDate ? admin_login.creationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a class="btn btn-primary my-1" href="{{ path('admin_login_show', {'id': admin_login.id}) }}">Afficher</a>
                    <a class="btn btn-primary my-1" href="{{ path('admin_login_edit', {'id': admin_login.id}) }}">Éditer</a>
                </td>
            </tr>
            {% else %}
            <tr>
                <td colspan="6">Aucune entrée</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
      
    </main>
  </div>
</div> {# end container-fluid #}

{% endblock %}

templates/admin_login/lostpw.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mot de passe oublié{% endblock %}

{% block body %}
{% block header %}{% endblock header %}
{% block dashboard %}{% endblock dashboard %}


<div class="container">
    <main role="main" class="col">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2 h2-swann">Vous avez oublié votre mot de passe ?</h1>
</div>
        <p>Entrez votre adresse email. Si votre compte existe, vous recevrez un email qui vous permettra de réinitialiser votre mot de passe.</p>
    <form method="POST">

        <input type="email" name="email">
        <button class="btn btn-primary" type="submit">Envoyer</button>
        <div>{{ messageConfirmation ?? "" }}</div>

        {% if messageConfirmation %}
    <script>
        function redirect() {
            window.setTimeout(function(){
        window.location.href = "http://127.0.0.1:8000/"
    }, 3000)
        }
        document.querySelector("form").addEventListener("submit", redirect());
    </script>
    {% endif %}
        
        {# <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}"> #}
        
    </form>

            </main>
</div> {# end container-fluid #}
{% endblock %}

templates/admin_login/new.html.twig
{% extends 'front-base.html.twig' %}

{% block title %}Inscription - Swann Xerri{% endblock %}

{% block body %}

<main id="inscription-page">   
        <section class="mtb">
            <div class="container-center cflex">  
            <h1>Créez votre compte</h1>
            {{ include('admin_login/_form.html.twig') }} 
            <p>Vous pourrez accéder à votre espace membre après l'activation de votre compte.</p>
            <strong>Veuillez consulter vos emails.</strong>

            {# <a href="{{ path('admin_login_index') }}">back to list</a> #}
            </div>{# end container center #}    
        </section>       
</main>
{% endblock %}

templates/admin_login/payment-confirm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement confirmé{% endblock %}

{% block body %}
{% block header %}{% endblock header %}
{% block dashboard %}{% endblock dashboard %}
<div class="container">
    <main role="main" class="col">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2 h2-swann">Confirmation de paiement</h1>
        </div>

        <p>Votre paiement a bien été enregistré.</p>
        <p>Vous allez être redirigé vers la page de création du compte d'accès à l'espace membre.</p>

    </main>
</div> {# end container-fluid #}
<script>
    window.setTimeout(function(){
        window.location.href = "http://127.0.0.1:8000/signup/";
        }, 5000);
</script>
{% endblock %}

templates/admin_login/resetpw.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau mot de passe{% endblock %}

{% block body %}
{% block header %}{% endblock header %}
{% block dashboard %}{% endblock dashboard %}


<div class="container">
    <main role="main" class="col">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <h1 class="h2 h2-swann">Formulaire de création d'un nouveau mot de passe.</h1>
        </div>
   
            <form method="POST">
                <div class="form-group">
                <label for="email">Votre email</label>
                <input class="form-control" type="email" name="email" value="{{ email }}"><br>
                <label for="cleActivation">Votre clé d'activation</label>
                <input class="form-control" type="text" name="cleActivation" value="{{ cleActivation }}"><br>
                <label for="password">Entrez votre nouveau mot de passe</label>
                <input class="form-control" id="password" type="password" name="password" placeholder="8 caractères minimum"><br>
                <label for="password">Confirmez votre nouveau mot de passe</label>
                <input class="form-control" id="password-confirm" type="password" name="password-confirm" placeholder="8 caractères minimum"><br>
                <input class="form-control" type="hidden" name="token" value="{token}">

                <button class="btn btn-primary" type="submit">Envoyer</button>
                <div>{{ messageConfirmation }}</div>

                {% if messageConfirmation %}
                <script>
                    function redirect() {
                        window.setTimeout(function(){
                    window.location.href = "http://127.0.0.1:8000/membres/"
                }, 3000)
                    }
                    document.querySelector("form").addEventListener("submit", redirect());
                </script>
            {% endif %}
            
                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
               </div> 
            </form>

            </main>
</div> {# end container-fluid #}
{% endblock %}

templates/admin_login/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}
    <h1>Affichage d'un utilisateur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ admin_login.id }}</td>
            </tr>
            <tr>
                <th>Nom d'utilisateur</th>
                <td>{{ admin_login.username }}</td>
            </tr>
            <tr>
                <th>Mot de passe</th>
                <td>{{ admin_login.password }}</td>
            </tr>
            <tr>
                <th>Niveau</th>
                <td>{{ admin_login.level }}</td>
            </tr>
            <tr>
                <th>Date de création</th>
                <td>{{ admin_login.creationDate ? admin_login.creationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('admin_login_index') }}">Retour à la liste</a>

    <a href="{{ path('admin_login_edit', {'id': admin_login.id}) }}">Éditer</a>

    {{ include('admin_login/_delete_form.html.twig') }}
{% endblock %}