src/Entity/ContactForm.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints as CaptchaAssert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactFormRepository")
 */
class ContactForm
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $objet;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_envoi;

    /**
     * @CaptchaAssert\ValidSimpleCaptcha(
     *      message = "CAPTCHA validation failed, try again."
     * )
     */
    protected $captchaCode;

    public function getCaptchaCode()
    {
        return $this->captchaCode;
    }

    public function setCaptchaCode($captchaCode)
    {
        $this->captchaCode = $captchaCode;
    }

    public function getId() : ? int
    {
        return $this->id;
    }

    public function getPrenom() : ? string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom) : self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom() : ? string
    {
        return $this->nom;
    }

    public function setNom(string $nom) : self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getObjet() : ? string
    {
        return $this->objet;
    }

    public function setObjet(string $objet) : self
    {
        $this->objet = $objet;

        return $this;
    }

    public function getEmail() : ? string
    {
        return $this->email;
    }

    public function setEmail(string $email) : self
    {
        $this->email = $email;

        return $this;
    }

    public function getContenu() : ? string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu) : self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateEnvoi() : ? \DateTimeInterface
    {
        return $this->date_envoi;
    }

    public function setDateEnvoi(\DateTimeInterface $date_envoi) : self
    {
        $this->date_envoi = $date_envoi;

        return $this;
    }
}

src/Form/ContactFormType.php
<?php

namespace App\Form;

use App\Entity\ContactForm;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Captcha\Bundle\CaptchaBundle\Form\Type\SimpleCaptchaType;

class ContactFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prenom', TextType::class, ["label" => "Prénom", "attr" => ["placeholder" => "Entrez votre prénom"]])
            ->add('nom', TextType::class, ["label" => "Nom", "attr" => ["placeholder" => "Entrez votre nom"]])
            ->add('email', TextType::class, ["label" => "Email", "attr" => ["placeholder" => "Entrez votre adresse email"]])
            ->add('objet', ChoiceType::class, ["choices" => ["Informations coaching personnel" => "Perso", "Informations coaching professionnel" => "Pro", "Informations conférences" => "Conférence", "Autre demande" => "Autre"]])
            ->add('contenu', TextareaType::class, ["label" => "Message", "attr" => ["placeholder" => "Quel est votre message ?", "rows" => "8" ]])
            ->add('captchaCode', SimpleCaptchaType::class, array(
                'captchaStyleName' => 'ExampleCaptcha'
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ContactForm::class,
        ]);
    }
}

src/Controller/ContactFormController.php
<?php

namespace App\Controller;

use App\Entity\ContactForm;
use App\Form\ContactFormType;
use App\Repository\ContactFormRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/contact")
 */
class ContactFormController extends AbstractController
{
    /**
     * @Route("/index", name="contact_form_index", methods={"GET"})
     */
    public function index(ContactFormRepository $contactFormRepository) : Response
    {
        return $this->render('contact_form/index.html.twig', [
            'contact_forms' => $contactFormRepository->findAll(),
        ]);
    }

    /**
     * @Route("/", name="contact", methods={"GET","POST"})
     */
    public function new(Request $request, \Swift_Mailer $mailer) : Response
    {
        $contactForm = new ContactForm();
        $form = $this->createForm(ContactFormType::class, $contactForm);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactForm->setDateEnvoi(new \DateTime);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contactForm);
            $entityManager->flush();

            $prenom = $contactForm->getPrenom();
            $contenu = $contactForm->getContenu();
            $objet = $contactForm->getObjet();
            $body = "<body style='text-align:center'><h3 style='color:red'>Bonjour, $prenom ! Votre message a bien été enregistré.</h3>
            <p>Je vous répondrai dans les plus brefs délais.</p>
            <div>Pour rappel, votre message était: <em>'$contenu'</em></div>
            </body>";

            $message = (new \Swift_Message("Swann Xerri - Contact"))
                ->setFrom("contact@swannxerri.com")
                ->setTo($contactForm->getEmail())
                ->setBody(
                    $body,
                    'text/html'
                );

            $mailer->send($message);

            $copyMessage = (new \Swift_Message("Demande de contact - $objet"))
                ->setFrom("contact@swannxerri.com")
                ->setTo("shinkansen13@gmail.com")
                ->setBody(
                    $contenu,
                    'text/html'
                );

            $mailer->send($copyMessage);

            return $this->redirectToRoute('contact_confirm');
        }

        return $this->render('contact_form/new.html.twig', [
            'contact_form' => $contactForm,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/index/{id}", name="contact_form_show", methods={"GET"})
     */
    public function show(ContactForm $contactForm) : Response
    {
        return $this->render('contact_form/show.html.twig', [
            'contact_form' => $contactForm,
        ]);
    }

    /**
     * @Route("/index/{id}/edit", name="contact_form_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ContactForm $contactForm) : Response
    {
        $form = $this->createForm(ContactFormType::class, $contactForm);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('contact_form_index', [
                'id' => $contactForm->getId(),
            ]);
        }

        return $this->render('contact_form/edit.html.twig', [
            'contact_form' => $contactForm,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/index/{id}", name="contact_form_delete", methods={"DELETE"})
     */
    public function delete(Request $request, ContactForm $contactForm) : Response
    {
        if ($this->isCsrfTokenValid('delete' . $contactForm->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($contactForm);
            $entityManager->flush();
        }

        return $this->redirectToRoute('contact_form_index');
    }

    /**
     * @Route("/contact_confirm", name="contact_confirm", methods={"GET"})
     */
    public function contactConfirmation(ContactFormRepository $contactFormRepository) : Response
    {
        return $this->render('confirmation-contact.html.twig', [
            'contact_forms' => $contactFormRepository->findAll(),
        ]);
    }
}

templates/contact_form/_delete_form.html.twig
<form method="post" action="{{ path('contact_form_delete', {'id': contact_form.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact_form.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contact_form/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn button">{{ button_label|default('Envoyer') }}</button>
{{ form_end(form) }}

templates/contact_form/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ContactForm{% endblock %}

{% block body %}
    <h1>Edit ContactForm</h1>

    {{ include('contact_form/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('contact_form_index') }}">back to list</a>

    {{ include('contact_form/_delete_form.html.twig') }}
{% endblock %}

templates/contact_form/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContactForm index{% endblock %}

{% block body %}
    <h1>ContactForm index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Objet</th>
                <th>Email</th>
                <th>Votre message</th>
                <th>Date d'envoi</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contact_form in contact_forms %}
            <tr>
                <td>{{ contact_form.id }}</td>
                <td>{{ contact_form.prenom }}</td>
                <td>{{ contact_form.nom }}</td>
                <td>{{ contact_form.objet }}</td>
                <td>{{ contact_form.email }}</td>
                <td>{{ contact_form.contenu }}</td>
                <td>{{ contact_form.dateEnvoi ? contact_form.dateEnvoi|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('contact_form_show', {'id': contact_form.id}) }}">show</a>
                    <a href="{{ path('contact_form_edit', {'id': contact_form.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('contact_form_new') }}">Create new</a>
{% endblock %}

templates/contact_form/new.html.twig
{% extends 'front-base.html.twig' %}

{% block title %}Contact - Swann Xerri{% endblock %}

{% block body %}

    <main id="contact-page">   
        <section class="cover cover-single cover-contact">
            <div class="cover-single__text">
				<h1 class="page-single-h1">Je suis là pour vous</h1>
            </div>
        </section>        
            <div class="container-center cflex">
                <section class="content-row">
                    <div class="content-left">
                        <div>
                            <h2>Prenez contact avec moi</h2>
                            <p class="contact-icons"><span class="icon"><img src="/assets/img/email.svg" alt=""></span> info@swannxerri.com</p>
                            <p class="contact-icons"><span class="icon"><img src="/assets/img/phone.svg" alt=""></span> +33 (0)6 45 39 87 11 </p>
                            <p class="contact-icons"><span class="icon"><img src="/assets/img/location.svg" alt=""></span> 44 Rue Paradis - 13001 Marseille</p>
                            <p class="">Afin que vous soyez à l'aise pour notre première prise de contact, choisissez le moyen qui vous convient le mieux.<p>
                            <p class="">Je peux intervenir aussi bien au niveau national qu'international.<p>
                        </div>
                    </div>
                    <div class="content-right">
                        <div class="content-right__text">
                            {{ include('contact_form/_form.html.twig') }}
                                <a href="{{ path('contact_form_index') }}">back to list</a>

                        </div>
                    </div>	
	            </section>
                
            </div>{# end container center #}        
    </main>
{% endblock %}

templates/contact_form/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContactForm{% endblock %}

{% block body %}
    <h1>ContactForm</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contact_form.id }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ contact_form.prenom }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ contact_form.nom }}</td>
            </tr>
            <tr>
                <th>Objet</th>
                <td>{{ contact_form.objet }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ contact_form.email }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ contact_form.contenu }}</td>
            </tr>
            <tr>
                <th>Date_envoi</th>
                <td>{{ contact_form.dateEnvoi ? contact_form.dateEnvoi|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('contact_form_index') }}">back to list</a>

    <a href="{{ path('contact_form_edit', {'id': contact_form.id}) }}">edit</a>

    {{ include('contact_form/_delete_form.html.twig') }}
{% endblock %}