src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $video;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $length;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_publication;

    public $uploadVideo;

    public function getId() : ? int
    {
        return $this->id;
    }

    public function getTitle() : ? string
    {
        return $this->title;
    }

    public function setTitle(string $title) : self
    {
        $this->title = $title;

        return $this;
    }

    public function getVideo() : ? string
    {
        return $this->video;
    }

    public function setVideo(string $video) : self
    {
        $this->video = $video;

        return $this;
    }

    public function getDescription() : ? string
    {
        return $this->description;
    }

    public function setDescription(string $description) : self
    {
        $this->description = $description;

        return $this;
    }

    public function getLength() : ? string
    {
        return $this->length;
    }

    public function setLength(string $length) : self
    {
        $this->length = $length;

        return $this;
    }

    public function getDatePublication() : ? \DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeInterface $date_publication) : self
    {
        $this->date_publication = $date_publication;

        return $this;
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, ["label" => "Titre"])
            ->add('video', TextType::class, ["label" => "Vidéo", "attr" => ["placeholder" => "Copier ici le lien d'intégration YouTube de la vidéo"]])
            ->add('description', TextType::class, ["label" => "Description"])
            ->add('length', TextType::class, ["label" => "Durée", "attr" => ["placeholder" => "Exemple - 00:00"]]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use App\Form\VideoType;
use App\Repository\VideoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/adminswann/video")
 */
class VideoController extends AbstractController
{
    /**
     * @Route("/", name="video_index", methods={"GET"})
     */
    public function index(VideoRepository $videoRepository) : Response
    {
        return $this->render('video/index.html.twig', [
            'videos' => $videoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="video_new", methods={"GET","POST"})
     */
    public function new(Request $request) : Response
    {
        $video = new Video();
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $video->setDatePublication(new \DateTime);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($video);
            $entityManager->flush();

            return $this->redirectToRoute('video_index');
        }

        return $this->render('video/new.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="video_show", methods={"GET"})
     */
    public function show(Video $video) : Response
    {
        return $this->render('video/show.html.twig', [
            'video' => $video,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="video_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Video $video) : Response
    {
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('video_index', [
                'id' => $video->getId(),
            ]);
        }

        return $this->render('video/edit.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="video_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Video $video) : Response
    {
        if ($this->isCsrfTokenValid('delete' . $video->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($video);
            $entityManager->flush();
        }

        return $this->redirectToRoute('video_index');
    }
}

templates/video/_delete_form.html.twig
<form method="post" action="{{ path('video_delete', {'id': video.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette entrée ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
    <button class="btn btn-danger mx-3">Supprimer</button>
</form>

templates/video/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/video/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Éditer une vidéo{% endblock %}

{% block body %}
<div class="container-fluid">
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">Éditer une vidéo</h1>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>

    {{ include('video/_form.html.twig', {'button_label': 'Mettre à jour'}) }}


    {{ include('video/_delete_form.html.twig') }}


        </main>
  </div>
</div> {# end container-fluid #}
{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des vidéos{% endblock %}

{% block body %}
<div class="container-fluid">
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">Liste des vidéos</h1>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Vidéo</th>
                <th>Description</th>
                <th>Durée</th>
                <th>Date de publication</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for video in videos %}
            <tr>
                <td>{{ video.id }}</td>
                <td>{{ video.title }}</td>
                <td>{{ video.video | raw }}</td>
                <td>{{ video.description }}</td>
                <td>{{ video.length }}</td>
                <td>{{ video.datePublication ? video.datePublication|date('d/m/Y H:i:s') : '' }}</td>
                <td>
                    <a class="btn btn-primary my-1" href="{{ path('video_show', {'id': video.id}) }}">Afficher</a>
                    <a class="btn btn-primary my-1" href="{{ path('video_edit', {'id': video.id}) }}">Éditer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        </main>
  </div>
</div> {# end container-fluid #}
{% endblock %}

templates/video/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle vidéo{% endblock %}

{% block body %}
<div class="container-fluid">
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">Ajout d'une nouvelle vidéo</h1>
      </div>
    {{ include('video/_form.html.twig') }}



    </main>
</div> {# end container-fluid #}
{% endblock %}

templates/video/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vidéo{% endblock %}

{% block body %}
    <h1>Détails</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ video.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ video.title }}</td>
            </tr>
            <tr>
                <th>Vidéo</th>
                <td>{{ video.video }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ video.description }}</td>
            </tr>
            <tr>
                <th>Durée</th>
                <td>{{ video.length }}</td>
            </tr>
            <tr>
                <th>Date de publication</th>
                <td>{{ video.datePublication ? video.datePublication|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('video_index') }}">Retour à la liste</a>

    <a href="{{ path('video_edit', {'id': video.id}) }}">Éditer</a>

    {{ include('video/_delete_form.html.twig') }}
{% endblock %}